/**
 * contractConfig.ts  (server-only)
 *
 * Utilities for loading deployed contract addresses and ABIs inside Next.js
 * API routes. Uses the same deployedContracts.ts that SE-2 generates after
 * `yarn deploy`, so addresses are always in sync with the local node.
 */
import { type Chain, type PublicClient, createPublicClient, http } from "viem";
import { hardhat } from "viem/chains";
import scaffoldConfig from "~~/scaffold.config";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Minimal shape we need from deployedContracts — only what the API routes use. */
export interface ContractConfig {
  address: `0x${string}`;
  abi: readonly unknown[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Return the target chain for API-route RPC calls.
 * Reads from scaffold.config.ts, same as the frontend.
 */
export function getTargetChain(): Chain {
  return (scaffoldConfig.targetNetworks[0] as Chain) ?? hardhat;
}

/**
 * Return an RPC URL for the target chain.
 * Uses rpcOverrides if configured, otherwise falls back to Hardhat's default.
 */
export function getRpcUrl(): string {
  const chain = getTargetChain();
  const overrides = (scaffoldConfig.rpcOverrides ?? {}) as Record<number, string>;
  return overrides[chain.id] ?? (chain.rpcUrls?.default?.http?.[0] as string) ?? "http://127.0.0.1:8545";
}

/**
 * Create a viem PublicClient configured for the target chain.
 * Used in API routes that need to read contract state.
 */
export function getPublicClient(): PublicClient {
  const chain = getTargetChain();
  return createPublicClient({
    chain,
    transport: http(getRpcUrl()),
  });
}

/**
 * Load the address and ABI for a named contract from deployedContracts.ts.
 * Throws a descriptive error if the contract hasn't been deployed yet.
 *
 * @param contractName - e.g. "BadgeTemplate", "BadgeMinter"
 */
export async function getContractConfig(contractName: string): Promise<ContractConfig> {
  let deployedContracts: Record<string, Record<string, { address: string; abi: readonly unknown[] }>>;

  try {
    // Dynamic import so missing file doesn't crash the whole module at load time.
    // The file is generated by `yarn deploy` — suppress the TS module-not-found error
    // until the first deploy runs.

    // @ts-ignore — generated after `yarn deploy`
    deployedContracts = (await import("~~/contracts/deployedContracts")).default;
  } catch {
    throw new Error(`deployedContracts.ts not found. Run "yarn deploy" to deploy contracts and generate the file.`);
  }

  const chain = getTargetChain();
  const chainContracts = deployedContracts[chain.id.toString()];

  if (!chainContracts) {
    throw new Error(`No contracts found for chain ID ${chain.id}. Run "yarn deploy --network <network>".`);
  }

  const contract = chainContracts[contractName];

  if (!contract) {
    throw new Error(
      `Contract "${contractName}" not found in deployedContracts for chain ${chain.id}. Did you deploy it?`,
    );
  }

  return {
    address: contract.address as `0x${string}`,
    abi: contract.abi,
  };
}
